server:
    port: 5001

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git: # 远程库的git地址
          uri: C:\Users\Brandon\Downloads\spring-cloud-netflix-learning\microservice-cloud-config.git