server:
  port: 80


eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

logging:
  level:
    com.uptoser.springcloud.netflix.service.ProductClientService: debug # Feign的日志打印只会对DEBUG级别做出响应

feign:
  hystrix:
    enabled: true # 开启服务熔断器
  compression:
    request:
      enabled: true # 启用Feign对请求的压缩功能
      mime-types: text/xml, application/xml, application/json # 媒体类型列表，默认是text/xml、application/xml以及application/json
      min-request-size: 2048 # 设置请求的最小阈值，默认是2048
    response:
      enabled: true # 启用Feign对响应的压缩功能
  client:
    config:
      default:
        connectTimeout: 5000 # 配置连接超时时间
        readTimeout: 5000 # 读取的超时时间
        loggerLevel: full # 配置日志级别，可选别的值如 NONE, BASIC, HEADERS, FULL
        #### Logger.Level的值有以下选择。
        ##### •NONE：不记录任何日志（默认值）。
        ##### •BASIC：仅记录请求方法、URL、响应状态代码以及执行时间。
        ##### •HEADERS：记录BASIC级别的基础上，记录请求和响应的header。
        ##### •FULL：记录请求和响应的header、body和元数据。
#        retryer: com.exampIe.SimpIeRetryer # 配置重试
#        errorDecoder: com.example.SimpleErrorDecoder # 配置错误解析码
#        request-interceptors: # 配置拦截器
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor

