server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

### 脱离Eureka使用Ribbon
#microservice-product:
#  ribbon:
#    listOfServers: localhost:8001,localhost:8002

## Ribbon从Spring Cloud Dalston开始可配置饥饿加载
ribbon:
  eager-load:
    enabled: true
    clients: microservice-product, microservice-order, microservice-bill